main_page = 'https://stellarburgers.nomoreparties.site/'
login_page = 'https://stellarburgers.nomoreparties.site/login'
order_history_page = 'https://stellarburgers.nomoreparties.site/feed'
register_page = 'https://stellarburgers.nomoreparties.site/register'
forgot_password_page = 'https://stellarburgers.nomoreparties.site/forgot-password'
account_page = 'https://stellarburgers.nomoreparties.site/account/profile'
